"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.WALLET_SIGN_SESSION = exports.VERSION = exports.REFUNDED_GAS = exports.METACHAIN_SHARD_ID = exports.LOGOUT_ACTION_NAME = exports.LOGIN_ACTION_NAME = exports.LEDGER_CONTRACT_DATA_ENABLED_VALUE = exports.GAS_PRICE_MODIFIER = exports.GAS_PRICE = exports.GAS_PER_DATA_BYTE = exports.GAS_LIMIT = exports.EXTRA_GAS_LIMIT_GUARDED_TX = exports.DIGITS = exports.DECIMALS = exports.CANCEL_ACTION_NAME = exports.ALL_SHARDS_SHARD_ID = void 0;
const GAS_PRICE_MODIFIER = 0.01;
exports.GAS_PRICE_MODIFIER = GAS_PRICE_MODIFIER;
const GAS_PER_DATA_BYTE = 1_500;
exports.GAS_PER_DATA_BYTE = GAS_PER_DATA_BYTE;
const GAS_LIMIT = 50_000;
/**
 * Extra gas limit for guarded transactions
 */
exports.GAS_LIMIT = GAS_LIMIT;
const EXTRA_GAS_LIMIT_GUARDED_TX = 50_000;
exports.EXTRA_GAS_LIMIT_GUARDED_TX = EXTRA_GAS_LIMIT_GUARDED_TX;
const GAS_PRICE = 1_000_000_000;
exports.GAS_PRICE = GAS_PRICE;
const DECIMALS = 18;
exports.DECIMALS = DECIMALS;
const DIGITS = 4;
exports.DIGITS = DIGITS;
const VERSION = 1;
exports.VERSION = VERSION;
const LEDGER_CONTRACT_DATA_ENABLED_VALUE = 1;
exports.LEDGER_CONTRACT_DATA_ENABLED_VALUE = LEDGER_CONTRACT_DATA_ENABLED_VALUE;
const METACHAIN_SHARD_ID = 4294967295;
exports.METACHAIN_SHARD_ID = METACHAIN_SHARD_ID;
const ALL_SHARDS_SHARD_ID = 4294967280;
exports.ALL_SHARDS_SHARD_ID = ALL_SHARDS_SHARD_ID;
const WALLET_SIGN_SESSION = 'signSession';
exports.WALLET_SIGN_SESSION = WALLET_SIGN_SESSION;
const LOGOUT_ACTION_NAME = 'logout';
exports.LOGOUT_ACTION_NAME = LOGOUT_ACTION_NAME;
const LOGIN_ACTION_NAME = 'login';
exports.LOGIN_ACTION_NAME = LOGIN_ACTION_NAME;
const CANCEL_ACTION_NAME = 'cancelSignTx';
exports.CANCEL_ACTION_NAME = CANCEL_ACTION_NAME;
const REFUNDED_GAS = 'refundedGas';
exports.REFUNDED_GAS = REFUNDED_GAS;
//# sourceMappingURL=gas.js.map